lang: pl_PL
title: Radosław Roszczyk
description: > # this means to ignore newlines until "baseurl:"
  To jest mój osobisty blog, służący wyrażaniu moich prywatnych opinii na różne tematy. Jest to również mój osobisty dziennik w&nbsp;którym dzielę się swoimi przemyśleniami oraz pomysłami dotyczącymi różnych spraw.
permalink: ':title/'
site:
  baseurl: "/" # the subpath of your site, e.g. /blog
  url: "https://rroszczyk.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#  url: "http://127.0.0.1:4000"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Radoslaw Roszczyk # add your name
author-img: radoslaw_roszczyk_192.jpg # add your photo
#about-author: I am a software developer, researcher, and academic. Always hungry to keep learning. # add description
#about-author: Thoughts, stories and ideas.
about-author: Przemyślenia, historie oraz nowe koncepcje.
social-twitter: rroszczyk # add your Twitter handle
social-facebook: rroszczy # add your Facebook handle
social-github: rroszczyk # add your Github handle
social-linkedin: rroszczyk # add your Linkedin handle
#social-email: # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-126717565-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"
permalink:             /:categories/:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

menu:
  - title:             Blog
    url:               /blog/
    
tag:  ""

collections:
  featured_tags:
    permalink:         /tags/:name/
    output:            true  

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]    